// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SheetYar.Infrastructure.Persistence;

#nullable disable

namespace SheetYar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SheetYarDbContext))]
    [Migration("20261008210054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SheetYar.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex("ActorUserId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AuditLogs_DetailsJson_Valid", "[DetailsJson] IS NULL OR ISJSON([DetailsJson]) = 1");

                            t.HasCheckConstraint("CK_AuditLogs_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AuditLogs_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedByIp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("RevokedByIp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenFamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AppUserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAfterCreated", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAtUtc_UTC", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_Replacement_NotSelf", "[ReplacedByTokenId] IS NULL OR [ReplacedByTokenId] <> [Id]");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedAfterCreated", "[RevokedAtUtc] IS NULL OR [RevokedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedAtUtc_UTC", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_RefreshTokens_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Files.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("WorkbookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("WorkbookId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("FileAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileAssets_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_FileAssets_Kind_Valid", "[Kind] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_FileAssets_Sha256_Valid", "LEN([Sha256]) = 64 AND [Sha256] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9A-Fa-f]%'");

                            t.HasCheckConstraint("CK_FileAssets_SizeBytes_NonNegative", "[SizeBytes] >= 0");

                            t.HasCheckConstraint("CK_FileAssets_StoragePath_Relative", "LEN(LTRIM(RTRIM([StoragePath]))) > 0 AND [StoragePath] NOT LIKE '%..%' AND CHARINDEX(':', [StoragePath]) = 0 AND CHARINDEX('\\', [StoragePath]) = 0 AND LEFT([StoragePath], 1) <> '/'");

                            t.HasCheckConstraint("CK_FileAssets_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_FileAssets_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Templates.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SourceFileAssetId")
                        .IsUnique()
                        .HasFilter("[SourceFileAssetId] IS NOT NULL");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Templates", null, t =>
                        {
                            t.HasCheckConstraint("CK_Templates_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Templates_SortOrder_NonNegative", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_Templates_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Templates_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("IsActive", "CreatedAtUtc");

                    b.ToTable("AppUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppUsers_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AppUsers_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AppUsers_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Workbooks.Workbook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("SourceTemplateId");

                    b.HasIndex("OwnerUserId", "UpdatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("Workbooks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workbooks_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Workbooks_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Workbooks_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Workbooks.WorkbookVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SnapshotFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkbookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SnapshotFileAssetId")
                        .IsUnique();

                    b.HasIndex("WorkbookId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("WorkbookId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("WorkbookVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkbookVersions_CreatedAtUtc_UTC", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_WorkbookVersions_UpdatedAtUtc_NotBeforeCreated", "[UpdatedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_WorkbookVersions_UpdatedAtUtc_UTC", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_WorkbookVersions_VersionNumber_Positive", "[VersionNumber] > 0");
                        });
                });

            modelBuilder.Entity("SheetYar.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("SheetYar.Domain.Users.AppUser", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("SheetYar.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("SheetYar.Domain.Users.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheetYar.Domain.Authentication.RefreshToken", "ReplacedByToken")
                        .WithMany("PreviousTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("ReplacedByToken");
                });

            modelBuilder.Entity("SheetYar.Domain.Files.FileAsset", b =>
                {
                    b.HasOne("SheetYar.Domain.Users.AppUser", "OwnerUser")
                        .WithMany("FileAssets")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SheetYar.Domain.Workbooks.Workbook", "Workbook")
                        .WithMany("FileAssets")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerUser");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("SheetYar.Domain.Templates.Template", b =>
                {
                    b.HasOne("SheetYar.Domain.Files.FileAsset", "SourceFileAsset")
                        .WithOne("SourceForTemplate")
                        .HasForeignKey("SheetYar.Domain.Templates.Template", "SourceFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceFileAsset");
                });

            modelBuilder.Entity("SheetYar.Domain.Workbooks.Workbook", b =>
                {
                    b.HasOne("SheetYar.Domain.Users.AppUser", "OwnerUser")
                        .WithMany("Workbooks")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SheetYar.Domain.Templates.Template", "SourceTemplate")
                        .WithMany("Workbooks")
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("SheetYar.Domain.Workbooks.WorkbookVersion", b =>
                {
                    b.HasOne("SheetYar.Domain.Users.AppUser", "CreatedByUser")
                        .WithMany("CreatedWorkbookVersions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SheetYar.Domain.Files.FileAsset", "SnapshotFileAsset")
                        .WithOne("SnapshotForVersion")
                        .HasForeignKey("SheetYar.Domain.Workbooks.WorkbookVersion", "SnapshotFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SheetYar.Domain.Workbooks.Workbook", "Workbook")
                        .WithMany("Versions")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("SnapshotFileAsset");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("SheetYar.Domain.Authentication.RefreshToken", b =>
                {
                    b.Navigation("PreviousTokens");
                });

            modelBuilder.Entity("SheetYar.Domain.Files.FileAsset", b =>
                {
                    b.Navigation("SnapshotForVersion");

                    b.Navigation("SourceForTemplate");
                });

            modelBuilder.Entity("SheetYar.Domain.Templates.Template", b =>
                {
                    b.Navigation("Workbooks");
                });

            modelBuilder.Entity("SheetYar.Domain.Users.AppUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedWorkbookVersions");

                    b.Navigation("FileAssets");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Workbooks");
                });

            modelBuilder.Entity("SheetYar.Domain.Workbooks.Workbook", b =>
                {
                    b.Navigation("FileAssets");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
